config/routes.rb
Rails.application.routes.draw do
  resources :news_items
  root 'news_items#index'

end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_action :set_news_item, only: [:show, :edit, :update, :destroy]

  # GET /news_items
  # GET /news_items.json
  def index
    @news_items = NewsItem.all
  end

  # GET /news_items/1
  # GET /news_items/1.json
  def show
  end

  # GET /news_items/new
  def new
    @news_item = NewsItem.new
  end


  # GET /news_items/1/edit
  def edit
  end

  # POST /news_items
  # POST /news_items.json
  def create
    @news_item = NewsItem.new(news_item_params)

    respond_to do |format|
      if @news_item.save
        format.html { redirect_to @news_item, notice: 'News item was successfully created.' }
        format.json { render :show, status: :created, location: @news_item }
      else
        format.html { render :new }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_items/1
  # PATCH/PUT /news_items/1.json
  def update
    respond_to do |format|
      if @news_item.update(news_item_params)
        format.html { redirect_to @news_item, notice: 'News item was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_item }
      else
        format.html { render :edit }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_items/1
  # DELETE /news_items/1.json
  def destroy
    @news_item.destroy
    respond_to do |format|
      format.html { redirect_to news_items_url, notice: 'News item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_item
      @news_item = NewsItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_item_params
      params.require(:news_item).permit(:title, :sub_header, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oldnews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news_items/_form.html.erb
<%= form_for(@news_item) do |f| %>
  <% if @news_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_item.errors.count, "error") %> prohibited this news_item from being saved:</h2>

      <ul>
      <% @news_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sub_header %><br>
    <%= f.text_area :sub_header %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_items/edit.html.erb
<h1>Editing News Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_item %> |
<%= link_to 'Back', news_items_path %>

app/views/news_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News!</h1>
<% @news_items.each do |news_item| %>
    <a href="<%= news_item_path news_item%>" class="summary">
      <%= image_tag(news_item.image.thumbnail.url, :class => "thumbnail inline") %>
      <h2><%= news_item.title %></h2>
      <h3><%= news_item.sub_header %></h3>
    </a>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Sub header</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_items.each do |news_item| %>
      <tr>
        <td><%= news_item.title %></td>
        <td><%= news_item.sub_header %></td>
        <td><%= news_item.content %></td>
        <td><%= link_to 'Show', news_item %></td>
        <td><%= link_to 'Edit', edit_news_item_path(news_item) %></td>
        <td><%= link_to 'Destroy', news_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News item', new_news_item_path %>

app/views/news_items/new.html.erb
<h1>New News Item</h1>

<%= render 'form' %>

<%= link_to 'Back', news_items_path %>

app/views/news_items/show.html.erb
<%= image_tag @news_item.image_url.to_s, class: 'bg' %>
<p id="notice"><%= notice %></p>

<div class="content">
<h1><%= @news_item.title %></h1>
<h2><%= @news_item.sub_header %></h2>
<p>
  <%= @news_item.content %>
</p>
</div>

<%= link_to 'Edit', edit_news_item_path(@news_item) %> |
<%= link_to 'Back', news_items_path %>